openapi: 3.0.3
info:
  title: Swagger Tech Challenge - OpenAPI 3.0
  description: |-
    This is a Tech Challenge Swagger based on the OpenAPI 3.0 specification.
    
    Some useful links:
    - [The Tech Challenge repository](https://github.com/guinegreiros-dev/tech-challenge-fiap-group-23)
    - [The source API definition for the Tech Challenge](https://github.com/guinegreiros-dev/tech-challenge-fiap-group-23/tree/main/docs/swagger/openapi.yaml)
  version: 1.0.0
servers:
  - url: http://localhost:8080
tags:
  - name: products
    description: Everything about products
paths:
  /products:
    post:
      tags:
        - products
      summary: Add a new product
      description: Add a product to the store
      requestBody:
        description: Create a new product in the store
        content:
          multipart/form-data:
            schema:
              $ref: '#/components/schemas/Product'
        required: true
      responses:
        '200':
          description: Created
        '400':
          description: bad request
        '500':
          description: internal error
  /products/categories/{id}:
    get:
      tags:
        - products 
      summary: Finds products by category
      description: List of products by category.
      parameters:
        - name: id
          in: path
          description: ID of category to return products
          required: true
          schema:
            type: integer
            format: int64
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/GetProduct'      
        '400':
          description: Bad Request
  /products/{id}:
    delete:
      tags:
        - products 
      summary: delete a product
      parameters:
        - name: id
          in: path
          description: ID of category to delete.
          required: true
          schema:
            type: number
      responses:
        '200':
          description: OK
        '400':
          description: Bad Request
        '404':
          description: Not Found
components:
  schemas:
    Product:
        type: object
        required:
        - categoryId
        - name
        - price
        properties: 
          categoryId:            
            type: string
            format: smallint
            description: "Enum values: 1: lanche, 2: acompanhamento, 3: bebida, 4: sobremesa"
            enum:
            - 1
            - 2
            - 3
            - 4
          description:
            type: string
          name:
            type: string
          price:
            type: string
            format: float
          image:
            type: string
            format: binary
    GetProduct:
        type: object
        properties: 
          id:
            type: integer
          categoryId:            
            type: integer
            description: "Enum values: 1: lanche, 2: acompanhamento, 3: bebida, 4: sobremesa"
          name:
            type: string
          description:
            type: string
          price:
            type: number
          image:
            type: object
            properties:
              type:
                type: string
              data:
                type: array
                items:
                  type: integer
          createdAt:
            type: string
          updatedAt:
            type: string