version: '3'
services:
  postgres:
    image: postgres:16
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: admin123
    ports:
      - 5432:5432
    volumes:
      - ./docs/db/migrations/1714749686_bootstrap.up.sql:/docker-entrypoint-initdb.d/1714749686_bootstrap.up.sql
      -  pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "sh -c 'pg_isready -U postgres'"]
      interval: 10s
      timeout: 3s
      retries: 3
  node_app:
    build:
      context: .
      dockerfile: Dockerfile
    env_file: .env.docker-dev
    command: sh -c 'pnpm dev'
    ports:
      - "3000:3000"
    depends_on:
      postgres:
        condition: service_healthy
    volumes:
      - .:/app
      - node_modules:/app/node_modules

volumes:
  pgdata:
  node_modules:
