version: '3'
services:
  postgres:
    image: postgres:16
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: admin123
    ports:
      - 5432:5432
    volumes:
      - postgres:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "sh -c 'pg_isready -U postgres'"]
      interval: 10s
      timeout: 3s
      retries: 3
  node_app:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      APP_PORT: 8080
      DATABASE_HOST: postgres
      DATABASE_USER: postgres
      DATABASE_PASSWORD: admin123
      DATABASE_PORT: 5432
      DATABASE: tech_challenge
      MERCADOPAGO_PORT: 3004
      MERCADOPAGO_DNS: mercadopago
    ports:
      - "8080:8080"
    depends_on:
      postgres:
        condition: service_healthy
    working_dir: /app
    volumes:
      - .:/app
      - node_modules:/app/node_modules
  mercadopago:
    build: .
    environment:
      MERCADOPAGO_PORT: 3004
    command: sh -c 'pnpm mock'
    ports:
      - "3004:3004"
    working_dir: /app

volumes:
  postgres:
  node_modules:
